### ISSUE TITLE
How to install on Debian stable "ctranslate2==1.17.1"

### ISSUE THREAD

**Issue by Sciss** [uav4geo/LibreTranslate#43]
Hi there! Cool project. I'm trying both direct install, or building via source. This is on Debian 10:

```
 $ pip3 install libretranslate
Collecting libretranslate
  Downloading https://files.pythonhosted.org/packages/de/2d/1c13e912914ddb0e2823810163e5c4a790a3275e980f67822e333b3860b8/libretranslate-1.1.0-py3-none-any.whl
...
Collecting ctranslate2==1.17.1 (from argostranslate==1.1.2->libretranslate)
  Could not find a version that satisfies the requirement ctranslate2==1.17.1 (from argostranslate==1.1.2->libretranslate) (from versions: )
No matching distribution found for ctranslate2==1.17.1 (from argostranslate==1.1.2->libretranslate)
```

```
$ git clone https://github.com/uav4geo/LibreTranslate
Cloning into 'LibreTranslate'...
...
$ cd LibreTranslate/
$ pip3 install -e .
Obtaining file:///home/x/Documents/devel/LibreTranslate
Collecting Flask-Limiter==1.4 (from libretranslate==1.1.0)
  Using cached https://files.pythonhosted.org/packages/1c/66/1bc848a3d37bed2a4c6cea7b7e39b830b2cd848dc7dde759926bb896f8e8/Flask_Limiter-1.4-py3-none-any.whl
...
Collecting ctranslate2==1.17.1 (from argostranslate==1.1.2->libretranslate==1.1.0)
  Could not find a version that satisfies the requirement ctranslate2==1.17.1 (from argostranslate==1.1.2->libretranslate==1.1.0) (from versions: )
No matching distribution found for ctranslate2==1.17.1 (from argostranslate==1.1.2->libretranslate==1.1.0)
```

or

```
$ python3 main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from app import main
  File "/home/x/Documents/devel/LibreTranslate/app/__init__.py", line 1, in <module>
    from .main import main
  File "/home/x/Documents/devel/LibreTranslate/app/main.py", line 2, in <module>
    from app.app import create_app
  File "/home/x/Documents/devel/LibreTranslate/app/app.py", line 1, in <module>
    from flask import Flask, render_template, jsonify, request, abort, send_from_directory
ModuleNotFoundError: No module named 'flask'
```

Python3 is 3.7.3.

Any hints?

**Comment by Sciss** [comment]
When I use `update-alternatives` to give priority to python 3 (so I can run `pip` instead of `pip3`), it runs a little longer but still fails:

```
$ pip install libretranslate
Collecting libretranslate
  Using cached https://files.pythonhosted.org/packages/de/2d/1c13e912914ddb0e2823810163e5c4a790a3275e980f67822e333b3860b8/libretranslate-1.1.0-py3-none-any.whl
...
Collecting PyQt5==5.15.1 (from argostranslate==1.1.2->libretranslate)
  Downloading https://files.pythonhosted.org/packages/1d/31/896dc3dfb6c81c70164019a6cbba6ab037e3af7653d9ca60ccc874ee4c27/PyQt5-5.15.1.tar.gz (3.3MB)
    100% |████████████████████████████████| 3.3MB 353kB/s 
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-wxifgoiv/PyQt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-wxifgoiv/PyQt5/
```

**Comment by Sciss** [comment]
Seems I ran into [this problem](https://stackoverflow.com/questions/48812195/filenotfounderror-installing-pyqt5). After running `pip  install --upgrade pip`, the call to `pip install libretranslate` succeeded.

**Comment by pierotofy** [comment]
Glad it worked!
