### ISSUE TITLE
[Docker] UnboundLocalError: local variable 'limiter' referenced before assignment

### ISSUE THREAD

**Issue by sigaloid** [uav4geo/LibreTranslate#49]
```
ubuntu@dns:~$ sudo docker run --restart unless-stopped -ti -p 127.0.0.1:5000:5000 libretranslate/libretranslate
Unable to find image 'libretranslate/libretranslate:latest' locally
latest: Pulling from libretranslate/libretranslate
0ecb575e629c: Pull complete 
7467d1831b69: Pull complete 
feab2c490a3c: Pull complete 
f15a0f46f8c3: Pull complete 
937782447ff6: Pull complete 
e78b7aaaab2c: Pull complete 
d6174e4a4e34: Pull complete 
45440a62f00d: Pull complete 
308e5e6db8bd: Pull complete 
59c4688e1459: Pull complete 
d57b72e02cb3: Pull complete 
c06705b84d78: Pull complete 
7f92627d08b8: Pull complete 
Digest: sha256:519a627fef1bdca6c61cfd39b5aeab424f4cbf11289a50f37fd45f7ec5645df9
Status: Downloaded newer image for libretranslate/libretranslate:latest
Updating language models
Found 16 models
Downloading Arabic -> English (1.0) ...
Downloading German -> English (1.0) ...
Downloading English -> Arabic (1.0) ...
Downloading English -> German (1.0) ...
Downloading English -> Spanish (1.0) ...
Downloading English -> French (1.0) ...
Downloading English -> Italian (1.0) ...
Downloading English -> Portuguese (1.0) ...
Downloading English -> Russian (1.0) ...
Downloading English -> Chinese (1.0) ...
Downloading Spanish -> English (1.0) ...
Downloading French -> English (1.0) ...
Downloading Italian -> English (1.0) ...
Downloading Portuguese -> English (1.0) ...
Downloading Russian -> English (1.0) ...
Downloading Chinese -> English (1.0) ...
Loaded support for 9 languages (16 models total)!
Traceback (most recent call last):
  File "/usr/local/bin/libretranslate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/app/main.py", line 35, in main
    app = create_app(args)
  File "/usr/local/lib/python3.8/site-packages/app/app.py", line 100, in create_app
    @limiter.exempt
UnboundLocalError: local variable 'limiter' referenced before assignment
```
Note the `restart` (I want it to auto start) and the `127.0.0.1`, should I instead have changed it with the arguments? Could this cause the issue?

**Comment by pierotofy** [comment]
Hey @sigaloid :hand: thanks for the report! This is a bug, which should be fixed with https://github.com/uav4geo/LibreTranslate/commit/3e952fbdb4dc809c2dda9852410295243f8f7dd7

Once the docker image has updated, please retry and see if the issue is solved? :pray:

**Comment by sigaloid** [comment]
Is re-running the same command sufficient to pull the latest docker image? If so, i'm pulling it right now.

**Comment by pierotofy** [comment]
You'll need to issue a `docker pull libretranslate/libretranslate` first.

**Comment by sigaloid** [comment]
```
ubuntu@dns:~$ sudo docker run --restart unless-stopped -ti -p 127.0.0.1:5000:5000 libretranslate/libretranslate
Updating language models
Found 16 models
Downloading Arabic -> English (1.0) ...
Downloading German -> English (1.0) ...
Downloading English -> Arabic (1.0) ...
Downloading English -> German (1.0) ...
Downloading English -> Spanish (1.0) ...
Downloading English -> French (1.0) ...
Downloading English -> Italian (1.0) ...
Downloading English -> Portuguese (1.0) ...
Downloading English -> Russian (1.0) ...
Downloading English -> Chinese (1.0) ...
Downloading Spanish -> English (1.0) ...
Downloading French -> English (1.0) ...
Downloading Italian -> English (1.0) ...
Downloading Portuguese -> English (1.0) ...
Downloading Russian -> English (1.0) ...
Downloading Chinese -> English (1.0) ...
Loaded support for 9 languages (16 models total)!
Serving on http://0.0.0.0:5000
```
However, I am unable to access the server through the reverse proxy. Trying 0.0.0.0 instead of 127.0.0.1 to see if it's the reverse proxy's fault. If I can't resolve it, I will open another issue as it seems unrelated.
