### ISSUE TITLE
You need to set an API key to translate on this server.

### ISSUE THREAD

**Issue by graysuit** [uav4geo/LibreTranslate#85]
**Code:**
```python
C:\Windows\System32>python
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 16:33:24) [MSC v.1928 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>>
>>> url = 'https://libretranslate.com/translate'
>>> data = {
... 'source': 'en',
... 'target': 'es',
... 'q': 'I live in Pakistan.'
... }
>>>
>>> x = requests.post(url, data = data)
>>> x.text
'{"error":"You need to set an API key to translate on this server."}\n'
````

How to generate api key ?
and is api key is paid for normal use ?

**Comment by pierotofy** [comment]
See #82

**Comment by pierotofy** [comment]
You should probably run your instance of LibreTranslate for the time being instead of using the API at libretranslate.com

**Comment by pierotofy** [comment]
Just merged #88  and #87; I've also updated libretranslate.com so you should be able to execute the code above. :+1: 

To get an API key get in touch at https://uav4geo.com/contact

**Comment by graysuit** [comment]
Nice to see this protection get implemented.
But what's the limit now ? like XX request per XX mint ?
And how longer bane would be ? 

And I also recommend to check for bot crawler like facebot, googlebot etc.
Whenever someone clicks on your site link on fb, the facebot will arrive on your site to get meta data and check site legality.
Same like, ....... on discord, the discord bot will arrive on your site to get meta data.
You need to NOT show them anything except meta tags like: `<meta ...>`
This code may help: https://github.com/DarkSecDevelopers/LitePhish/blob/main/modules/detect_bot.php

**Comment by pierotofy** [comment]
15 requests per minute, max 100 requests per day. 

Ban is in effect for 4 weeks. 5 violations get you a ban.

These might change in the future.

**Comment by graysuit** [comment]
`100 requests per day`
Need to be revised.

**Comment by pierotofy** [comment]
If you need more, run your own server?

**Comment by graysuit** [comment]
That's right. I would have, but nor it build easily, nor it installed via pip due to errors. 
Nor docker is available for 32 bit windows. 

Are there any compiled builds for windows ?
I have tried:
- pip/pip3 install libretranslate
```cmd
C:\LibreTranslate>pip install libretranslate --user
Collecting libretranslate
  Using cached https://files.pythonhosted.org/packages/b0/c0/6792409a063c225c4c38e5e267e87f0c136f079b2801128f5abcdcf1f13d/libretranslate-1.2.3-py3-none-any.whl
Collecting polyglot==16.7.4 (from libretranslate)
  Using cached https://files.pythonhosted.org/packages/e7/98/e24e2489114c5112b083714277204d92d372f5bbe00d5507acf40370edb9/polyglot-16.7.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\gray\AppData\Local\Temp\pip-install-2w4vkiuw\polyglot\setup.py", line 15, in <module>
        readme = readme_file.read()
      File "c:\program files\python37-32\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4941: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\gray\AppData\Local\Temp\pip-install-2w4vkiuw\polyglot\
You are using pip version 19.0.3, however version 21.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\LibreTranslate>
```
- pip install -e
```cmd
C:\LibreTranslate>pip3 install -e .
Obtaining file:///C:/LibreTranslate
Collecting argostranslate==1.1.4 (from libretranslate==1.2.3)
  Using cached https://files.pythonhosted.org/packages/4b/14/496477374822e28e0c0f4f5ca957a38f13e10aff4618894f5540cb73eb12/argostranslate-1.1.4-py3-none-any.whl
Collecting Flask==1.1.2 (from libretranslate==1.2.3)
  Using cached https://files.pythonhosted.org/packages/f2/28/2a03252dfb9ebf377f40fba6a7841b47083260bf8bd8e737b0c6952df83f/Flask-1.1.2-py2.py3-none-any.whl
Collecting flask-swagger==0.2.14 (from libretranslate==1.2.3)
  Using cached https://files.pythonhosted.org/packages/b2/a9/a6c05fbc592ac482bf9557e47957c429d2be8cb8addfbc92853fb862ea8f/flask-swagger-0.2.14.tar.gz
Collecting flask-swagger-ui==3.36.0 (from libretranslate==1.2.3)
  Using cached https://files.pythonhosted.org/packages/ee/54/52e6ee2bb83b2f778a83627019f4e3ccb9453e788da4418180c86b74ff07/flask-swagger-ui-3.36.0.tar.gz
Collecting Flask-Limiter==1.4 (from libretranslate==1.2.3)
  Using cached https://files.pythonhosted.org/packages/1c/66/1bc848a3d37bed2a4c6cea7b7e39b830b2cd848dc7dde759926bb896f8e8/Flask_Limiter-1.4-py3-none-any.whl
Collecting waitress==1.4.4 (from libretranslate==1.2.3)
  Using cached https://files.pythonhosted.org/packages/26/d1/5209fb8c764497a592363c47054436a515b47b8c3e4970ddd7184f088857/waitress-1.4.4-py2.py3-none-any.whl
Collecting expiringdict==1.2.1 (from libretranslate==1.2.3)
  Using cached https://files.pythonhosted.org/packages/65/8d/f7187039bfbdaa693f55e45f62a189ddbc7b514e3c8687e3d3e4420f2862/expiringdict-1.2.1.tar.gz
Collecting pyicu==2.6 (from libretranslate==1.2.3)
  Using cached https://files.pythonhosted.org/packages/31/46/fa08c8efae2951e67681ec24319f789fc1a74e2096dd74373e34c79319de/PyICU-2.6.tar.gz
    Complete output from command python setup.py egg_info:
    (running 'icu-config --version')
    (running 'pkg-config --modversion icu-i18n')
    Traceback (most recent call last):
      File "C:\Users\gray\AppData\Local\Temp\pip-install-8eavh5z3\pyicu\setup.py", line 63, in <module>
        ICU_VERSION = os.environ['ICU_VERSION']
      File "c:\program files\python37-32\lib\os.py", line 678, in __getitem__
        raise KeyError(key) from None
    KeyError: 'ICU_VERSION'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\gray\AppData\Local\Temp\pip-install-8eavh5z3\pyicu\setup.py", line 66, in <module>
        ICU_VERSION = check_output(('icu-config', '--version')).strip()
      File "C:\Users\gray\AppData\Local\Temp\pip-install-8eavh5z3\pyicu\setup.py", line 19, in check_output
        return subprocess_check_output(popenargs)
      File "c:\program files\python37-32\lib\subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "c:\program files\python37-32\lib\subprocess.py", line 472, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\program files\python37-32\lib\subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "c:\program files\python37-32\lib\subprocess.py", line 1178, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\gray\AppData\Local\Temp\pip-install-8eavh5z3\pyicu\setup.py", line 69, in <module>
        ICU_VERSION = check_output(('pkg-config', '--modversion', 'icu-i18n')).strip()
      File "C:\Users\gray\AppData\Local\Temp\pip-install-8eavh5z3\pyicu\setup.py", line 19, in check_output
        return subprocess_check_output(popenargs)
      File "c:\program files\python37-32\lib\subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "c:\program files\python37-32\lib\subprocess.py", line 472, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\program files\python37-32\lib\subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "c:\program files\python37-32\lib\subprocess.py", line 1178, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\gray\AppData\Local\Temp\pip-install-8eavh5z3\pyicu\setup.py", line 74, in <module>
        ''')
    RuntimeError:
    Please install pkg-config on your system or set the ICU_VERSION environment
    variable to the version of ICU you have installed.


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\gray\AppData\Local\Temp\pip-install-8eavh5z3\pyicu\
You are using pip version 19.0.3, however version 21.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\LibreTranslate>
```
- I also tried followed instructions at https://github.com/aboSamoor/polyglot/issues/127
```cmd
C:\LibreTranslate>python -m pip install C:\Users\gray\Downloads\pycld2-0.41-cp37-cp37m-win32.whl --user
Processing c:\users\gray\downloads\pycld2-0.41-cp37-cp37m-win32.whl
libretranslate 1.2.3 requires APScheduler==3.7.0, which is not installed.
libretranslate 1.2.3 requires argostranslate==1.1.4, which is not installed.
libretranslate 1.2.3 requires expiringdict==1.2.1, which is not installed.
libretranslate 1.2.3 requires Flask==1.1.2, which is not installed.
libretranslate 1.2.3 requires Flask-Limiter==1.4, which is not installed.
libretranslate 1.2.3 requires flask-swagger==0.2.14, which is not installed.
libretranslate 1.2.3 requires flask-swagger-ui==3.36.0, which is not installed.
libretranslate 1.2.3 requires morfessor==2.0.6, which is not installed.
libretranslate 1.2.3 requires polyglot==16.7.4, which is not installed.
libretranslate 1.2.3 requires waitress==1.4.4, which is not installed.
libretranslate 1.2.3 has requirement pyicu==2.6, but you'll have pyicu 2.7.3 which is incompatible.
Installing collected packages: pycld2
Successfully installed pycld2-0.41
You are using pip version 19.0.3, however version 21.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by pierotofy** [comment]
Yeah on Windows you're likely not going to be able to run it outside docker.

You could rent a cheap linux machine from somewhere like https://digitalocean.com as an alternative.

**Comment by PJ-Finlay** [comment]
CTranslate2 doesn't have binaries for Windows, Docker is probably the easiest way to run Argos Translate on Windows. (WSL might also be possible)

**Comment by graysuit** [comment]
Hi guys I have done almost everything, but failed badly.
Docker need:
- latest windows 10
- 64 bit
- even has problem while installation
WSL almost has same cases.

In other words, I need to install linux. That's it ?
Do you ever tried to run it on linux VM ? Does it works under Virtualbox ?

**Comment by PJ-Finlay** [comment]
If docker and WSL don't work then you could try:
- Run a Linux VM in Virtualbox
- Install Linux (Distros like Ubuntu make it easy to install Linux alongside Windows)
- Compile CTranslate2 for Windows

**Comment by graysuit** [comment]
I failed. It won't compile on linux too. Almost same errors.
I tried every option except dual boot, because my pc is slow, and can't afford that.
I'm almost about to give up.

Can you extend the request limit please ? 
I suggest, you can also make system like 
- anonymous users (100 requests per day)
- free registered users (1,000 requests per day)
- Premium registered users (10,000 requests per day)
or something like that to support the server.

**Comment by PJ-Finlay** [comment]
It's probably easiest to point to one of the [LibreTranslate mirrors](https://github.com/uav4geo/LibreTranslate/issues/78).
